In [10]:
import numpy as np
import sys

In [4]:
matriz = np.array([1,2,3,4,5])
matriz

array([1, 2, 3, 4, 5])

In [3]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matriz.shape

(2, 3)

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3))

array([1., 1., 1.])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
matriz = np.array([[1,2,4,],[4,5,6,]])
matriz

array([[1, 2, 4],
       [4, 5, 6]])

In [6]:
matriz = np.arange(15).reshape(3,5)
matriz
matriz.shape # cuantas filas y columnas tiene disponible la matriz
matriz.ndim # el numero de dimensiones de la matriz
matriz.size # l numero totral de elementos que posee la matriz

15

In [7]:
matriz = np.arange(27).reshape(3,3,3)
matriz

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
# diferencia entre una matriz y un array
lista = [[1,2,3],[4,5,6]]
array = np.array([[1,2,3],[4,5,6]])

In [14]:
# verificamos el tamaño en byte de un objeto
sys.getsizeof(lista)

72

In [15]:
sys.getsizeof(array) # el array es pequeño no se ve la diferencia con array rinde mas la memoria

168

In [19]:
%%timeit

sum(range(100000))

2.83 ms ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
np.array([1.3,2.4]).dtype

dtype('float64')

In [20]:
%%timeit
np.sum(np.arange(100000))

231 µs ± 2.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
matriz_34 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
matriz_34[0]

array([1, 2, 3, 4])

In [25]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
matriz_34[:,1] # seleccionamos el segundo elemento de cada sila

array([ 2,  6, 10])

In [28]:
matriz_34[1,1] # seleccionamos el segundo elemento de la fila 2

6

In [29]:
m1 = np.array([0,1,2,3,4])
m2= np.array([5,6,7,8,9])
m1+m2

array([ 5,  7,  9, 11, 13])

In [32]:
array = np.array([[1,6,11],
                  [2,7,12],
                  [3,8,13],
                  [4,9,14],
                  [5,10,15]
                ])
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [33]:
array.shape # forma del array

(5, 3)

In [36]:
array[:,1] #seleccionamos 2da columna

array([ 6,  7,  8,  9, 10])

In [38]:
array2 = np.arange(15,56) #creamos vector
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [39]:
array2[4]= 23 #cambiamos el valor en la quinta pocision
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [41]:
np.flip(array2) # invertimos el array

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [42]:
array2[::-1] # otra forma de invertir el array

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [44]:
matriz_diagonal =np.diag(array2[1::2][:5]) #matriz diagonal con valores pares de array2
matriz_diagonal

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [45]:
matriz_diagonal.ndim

2

In [47]:
matriz2 = np.random.random((5,3)) # matriz con numeros aleatorios
matriz2

array([[0.06483607, 0.40234654, 0.74980931],
       [0.90517263, 0.61195284, 0.44875211],
       [0.09095448, 0.04230424, 0.11718934],
       [0.47737453, 0.53575708, 0.4559189 ],
       [0.55547062, 0.42052929, 0.78640271]])

In [48]:
matriz2.shape

(5, 3)

In [49]:
matriz_diagonal.shape

(5, 5)

In [51]:
matriz_T = matriz2.T #trapuestas de un matriz para poder multipicarla
matriz_T

array([[0.06483607, 0.90517263, 0.09095448, 0.47737453, 0.55547062],
       [0.40234654, 0.61195284, 0.04230424, 0.53575708, 0.42052929],
       [0.74980931, 0.44875211, 0.11718934, 0.4559189 , 0.78640271]])

In [52]:
matriz_T @ matriz_diagonal

array([[ 1.03737719, 16.29310738,  1.81908967, 10.50223975, 13.33129477],
       [ 6.43754462, 11.01515112,  0.84608477, 11.78665565, 10.09270307],
       [11.99694901,  8.07753797,  2.34378685, 10.03021586, 18.87366513]])

### version de Numpy

In [9]:
np.__version__

'1.20.1'

In [10]:
cero = np.zeros(10)
cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
one = np.ones(10)*8
one

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

### Funcion arange()

In [13]:
ar = np.arange(20,51)
ar


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
ar = np.arange(20,51,2) # numeros pares
ar

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [15]:
ar = np.arange(0,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
ar = np.arange(15,55)
ar

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [17]:
ar[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [18]:
matriz = np.arange(1,13).reshape((4,3))#dimenciones a la matriz
matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
for elemento in np.nditer(matriz):#iterar los elementos dentro de la matriz
    print(elemento,end = ' ')

1 2 3 4 5 6 7 8 9 10 11 12 

### linspace (distribucion uniforme)

In [24]:
arre = np.linspace(10,50,5) 
arre

array([10., 20., 30., 40., 50.])

### Identidad

In [21]:
ident = np.identity(3)
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Aleatorio

In [22]:
aleat = np.random.random()
aleat

0.597680215222285

In [25]:
aleat = np.random.normal(0,1,10)
aleat

array([-1.71389958, -0.20603884, -0.1852869 ,  0.48663171,  0.71425085,
        0.01842033,  0.34193833,  0.70186717,  0.78093523, -0.11558198])