In [3]:
import numpy as np

In [4]:
matriz = np.array([1,2,3,4,5])
matriz

array([1, 2, 3, 4, 5])

In [5]:
matriz = np.array([[1,2,4,],[4,5,6,]])
matriz

array([[1, 2, 4],
       [4, 5, 6]])

In [6]:
matriz = np.arange(15).reshape(3,5)
matriz
matriz.shape # cuantas filas y columnas tiene disponible la matriz
matriz.ndim # el numero de dimensiones de la matriz
matriz.size # l numero totral de elementos que posee la matriz

15

In [7]:
matriz = np.arange(27).reshape(3,3,3)
matriz

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
m1 = np.array([0,1,2,3,4])
m2= np.array([5,6,7,8,9])
m1+m2

array([ 5,  7,  9, 11, 13])

### version de Numpy

In [9]:
np.__version__

'1.20.1'

In [10]:
cero = np.zeros(10)
cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
one = np.ones(10)*8
one

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

### Funcion arange()

In [13]:
ar = np.arange(20,51)
ar


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
ar = np.arange(20,51,2) # numeros pares
ar

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [15]:
ar = np.arange(0,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
ar = np.arange(15,55)
ar

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [17]:
ar[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [18]:
matriz = np.arange(1,13).reshape((4,3))#dimenciones a la matriz
matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
for elemento in np.nditer(matriz):#iterar los elementos dentro de la matriz
    print(elemento,end = ' ')

1 2 3 4 5 6 7 8 9 10 11 12 

### linspace (distribucion uniforme)

In [24]:
arre = np.linspace(10,50,5) 
arre

array([10., 20., 30., 40., 50.])

### Identidad

In [21]:
ident = np.identity(3)
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Aleatorio

In [22]:
aleat = np.random.random()
aleat

0.597680215222285

In [25]:
aleat = np.random.normal(0,1,10)
aleat

array([-1.71389958, -0.20603884, -0.1852869 ,  0.48663171,  0.71425085,
        0.01842033,  0.34193833,  0.70186717,  0.78093523, -0.11558198])